# SPDX-FileCopyrightText: 2024 Samuel Wu
#
# SPDX-License-Identifier: 0BSD

version = 1

[[annotations]]
path = ["assets/**", "files/**", "images/**"]
SPDX-FileCopyrightText = "2024 Samuel Wu"
SPDX-License-Identifier = "CC-BY-NC-SA-4.0"

[[annotations]]
path = ["README.md"]
SPDX-FileCopyrightText = "2024 Samuel Wu"
SPDX-License-Identifier = "0BSD"
